import { StrictMode } from 'react'
import { createRoot } from 'react-dom/client'
import { BrowserRouter, Navigate, Route, Routes } from 'react-router-dom'
import { AuthProvider } from './context/AuthContext'
import ProtectedRoute from './components/ProtectedRoute'
import DashboardLayout from './layouts/DashboardLayout'
import Login from './pages/Login'
import Register from './pages/Register'
import Dashboard from './pages/Dashboard'
import Reports from './pages/Reports'
import Profile from './pages/Profile'
import NotFound from './pages/NotFound'
import './styles.css'
const PrivateLayout = () => <ProtectedRoute><DashboardLayout/></ProtectedRoute>
createRoot(document.getElementById('root')).render(<StrictMode><BrowserRouter><AuthProvider><Routes><Route path="/" element={<Navigate to="/dashboard" replace/>}/><Route path="/login" element={<Login/>}/><Route path="/register" element={<Register/>}/><Route element={<PrivateLayout/>}><Route path="/dashboard" element={<Dashboard/>}/><Route path="/reports" element={<Reports/>}/><Route path="/profile" element={<Profile/>}/></Route><Route path="*" element={<NotFound/>}/></Routes></AuthProvider></BrowserRouter></StrictMode>)
